export const ADMIN_API_FAILURE_ACTIONS = {
  users: "ADMIN_USERS_API_FAILED",
  forumModeration: "ADMIN_FORUM_MODERATION_API_FAILED",
  router: "ADMIN_ROUTER_API_FAILED",
  prompts: "ADMIN_PROMPTS_API_FAILED",
  keys: "ADMIN_KEYS_API_FAILED",
  appointments: "ADMIN_APPOINTMENTS_API_FAILED",
  content: "ADMIN_CONTENT_API_FAILED",
} as const;

export const ALL_ADMIN_API_FAILURE_ACTIONS = Object.values(ADMIN_API_FAILURE_ACTIONS);
